-- booking_registers entry-id migration
-- Purpose:
--   1) Ensure booking_registers.id is a generated booking entry id.
--   2) Enforce one row per (platform_id, metadata.booking_id).
--   3) Remove legacy metadata.raw payload.
--   4) Update create/upsert functions to support p_id => NULL upserts.

DO $$
BEGIN
    IF to_regclass('public.booking_registers') IS NULL THEN
        RAISE EXCEPTION 'Missing table booking_registers. Run booking_registers.sql first.';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = 'booking_registers'
          AND a.attname = 'id'
          AND a.attidentity IN ('a', 'd')
    ) THEN
        EXECUTE 'ALTER TABLE booking_registers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
    END IF;
END $$;

DO $$
DECLARE
    v_seq_name TEXT;
    v_max_id BIGINT;
BEGIN
    SELECT pg_get_serial_sequence('booking_registers', 'id')
    INTO v_seq_name;

    IF v_seq_name IS NOT NULL THEN
        SELECT COALESCE(MAX(id), 0) INTO v_max_id FROM booking_registers;
        IF v_max_id > 0 THEN
            EXECUTE format('SELECT setval(%L, %s, true)', v_seq_name, v_max_id);
        ELSE
            EXECUTE format('SELECT setval(%L, 1, false)', v_seq_name);
        END IF;
    END IF;
END $$;

DO $$
DECLARE
    v_duplicate_group_count INT;
BEGIN
    SELECT COUNT(*) INTO v_duplicate_group_count
    FROM (
        SELECT
            br.platform_id,
            br.metadata->>'booking_id' AS external_booking_id
        FROM booking_registers br
        WHERE br.metadata->>'booking_id' IS NOT NULL
          AND BTRIM(br.metadata->>'booking_id') <> ''
        GROUP BY br.platform_id, br.metadata->>'booking_id'
        HAVING COUNT(*) > 1
    ) dup;

    IF v_duplicate_group_count > 0 THEN
        RAISE EXCEPTION
            'Cannot add unique external booking index: found % duplicate (platform_id, metadata.booking_id) groups',
            v_duplicate_group_count;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_registers_platform_external_booking_id
    ON booking_registers (platform_id, (metadata->>'booking_id'))
    WHERE metadata->>'booking_id' IS NOT NULL
      AND BTRIM(metadata->>'booking_id') <> '';

UPDATE booking_registers
SET metadata = metadata - 'raw'
WHERE metadata ? 'raw';

CREATE OR REPLACE FUNCTION create_booking_register(
    p_id BIGINT DEFAULT NULL,
    p_type TEXT DEFAULT 'booking',
    p_arrival DATE DEFAULT NULL,
    p_departure DATE DEFAULT NULL,
    p_booked_at TIMESTAMPTZ DEFAULT NULL,
    p_guest_id BIGINT DEFAULT NULL,
    p_platform_id INT DEFAULT NULL,
    p_listing_id TEXT DEFAULT NULL,
    p_thread_ids_json JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT '{}'::JSONB
) RETURNS booking_registers AS $$
DECLARE
    v_lookup RECORD;
    v_metadata JSONB;
    v_row booking_registers%ROWTYPE;
BEGIN
    SELECT *
    INTO v_lookup
    FROM resolve_booking_register_lookup(p_platform_id, p_listing_id);

    v_metadata := normalize_booking_register_metadata(p_metadata, p_listing_id);

    IF p_id IS NULL THEN
        INSERT INTO booking_registers (
            type,
            arrival,
            departure,
            booked_at,
            guest_id,
            property_id,
            platform_id,
            ppl_id,
            thread_ids_json,
            metadata
        )
        VALUES (
            COALESCE(NULLIF(BTRIM(p_type), ''), 'booking'),
            p_arrival,
            p_departure,
            p_booked_at,
            p_guest_id,
            v_lookup.property_id,
            p_platform_id,
            v_lookup.ppl_id,
            p_thread_ids_json,
            v_metadata
        )
        RETURNING *
        INTO v_row;
    ELSE
        INSERT INTO booking_registers (
            id,
            type,
            arrival,
            departure,
            booked_at,
            guest_id,
            property_id,
            platform_id,
            ppl_id,
            thread_ids_json,
            metadata
        )
        VALUES (
            p_id,
            COALESCE(NULLIF(BTRIM(p_type), ''), 'booking'),
            p_arrival,
            p_departure,
            p_booked_at,
            p_guest_id,
            v_lookup.property_id,
            p_platform_id,
            v_lookup.ppl_id,
            p_thread_ids_json,
            v_metadata
        )
        RETURNING *
        INTO v_row;
    END IF;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION upsert_booking_register(
    p_id BIGINT DEFAULT NULL,
    p_type TEXT DEFAULT NULL,
    p_arrival DATE DEFAULT NULL,
    p_departure DATE DEFAULT NULL,
    p_booked_at TIMESTAMPTZ DEFAULT NULL,
    p_guest_id BIGINT DEFAULT NULL,
    p_platform_id INT DEFAULT NULL,
    p_listing_id TEXT DEFAULT NULL,
    p_thread_ids_json JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT NULL
) RETURNS booking_registers AS $$
DECLARE
    v_external_booking_id TEXT := NULLIF(BTRIM(COALESCE(p_metadata->>'booking_id', '')), '');
BEGIN
    IF p_id IS NULL AND p_platform_id IS NOT NULL AND v_external_booking_id IS NOT NULL THEN
        SELECT br.id
        INTO p_id
        FROM booking_registers br
        WHERE br.platform_id = p_platform_id
          AND br.metadata->>'booking_id' = v_external_booking_id
        ORDER BY br.id DESC
        LIMIT 1;
    END IF;

    IF p_id IS NULL THEN
        BEGIN
            RETURN create_booking_register(
                p_id => NULL,
                p_type => COALESCE(p_type, 'booking'),
                p_arrival => p_arrival,
                p_departure => p_departure,
                p_booked_at => p_booked_at,
                p_guest_id => p_guest_id,
                p_platform_id => p_platform_id,
                p_listing_id => p_listing_id,
                p_thread_ids_json => p_thread_ids_json,
                p_metadata => COALESCE(p_metadata, '{}'::jsonb)
            );
        EXCEPTION
            WHEN unique_violation THEN
                IF p_platform_id IS NOT NULL AND v_external_booking_id IS NOT NULL THEN
                    SELECT br.id
                    INTO p_id
                    FROM booking_registers br
                    WHERE br.platform_id = p_platform_id
                      AND br.metadata->>'booking_id' = v_external_booking_id
                    ORDER BY br.id DESC
                    LIMIT 1;
                END IF;

                IF p_id IS NULL THEN
                    RAISE;
                END IF;
        END;
    END IF;

    BEGIN
        RETURN create_booking_register(
            p_id => p_id,
            p_type => COALESCE(p_type, 'booking'),
            p_arrival => p_arrival,
            p_departure => p_departure,
            p_booked_at => p_booked_at,
            p_guest_id => p_guest_id,
            p_platform_id => p_platform_id,
            p_listing_id => p_listing_id,
            p_thread_ids_json => p_thread_ids_json,
            p_metadata => COALESCE(p_metadata, '{}'::jsonb)
        );
    EXCEPTION
        WHEN unique_violation THEN
            RETURN update_booking_register(
                p_id => p_id,
                p_type => p_type,
                p_arrival => p_arrival,
                p_departure => p_departure,
                p_booked_at => p_booked_at,
                p_guest_id => p_guest_id,
                p_platform_id => p_platform_id,
                p_listing_id => p_listing_id,
                p_thread_ids_json => p_thread_ids_json,
                p_metadata => p_metadata
            );
    END;
END;
$$ LANGUAGE plpgsql;
