-- ============================================
-- BOOKING REGISTERS TABLE
-- ============================================
-- Run AFTER: property_platform_sql.sql
--
-- Stores all booking data with embedded metadata (JSONB).
--
-- Search paths supported:
--   1. booking entry id           -> id (PRIMARY KEY)
--   2. arrival / departure dates  -> idx_booking_registers_arrival,
--                                    idx_booking_registers_departure,
--                                    idx_booking_registers_scanner (composite)
--   3. ppl_id                     -> idx_booking_registers_ppl_id
--   4. property_id                -> idx_booking_registers_property_id
--   5. platform_id                -> idx_booking_registers_platform_id
--   6. metadata.booking_id        -> idx_booking_registers_meta_booking_id
--   7. metadata.listing_id        -> idx_booking_registers_meta_listing_id
--   8. metadata.bso.cancelled     -> idx_booking_registers_meta_cancelled
--   9. metadata.bso
--        .potential_extension
--        .last_extended           -> idx_booking_registers_meta_last_extended
--   10. Full JSONB metadata search -> idx_booking_registers_metadata_gin
--   11. thread_ids_json            -> idx_booking_registers_thread_ids_gin
-- ============================================

-- ============================================
-- 1) Table definition
-- ============================================
DROP TABLE IF EXISTS booking_registers;

CREATE TABLE IF NOT EXISTS booking_registers (

    -- -- Core identity ------------------------------------------------------
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY
                                    PRIMARY KEY,                 -- booking entry id
    type            TEXT            NOT NULL DEFAULT 'booking',

    -- -- Date range ---------------------------------------------------------
    arrival         DATE            NOT NULL,
    departure       DATE            NOT NULL,

    -- -- Booking facts ------------------------------------------------------
    booked_at       TIMESTAMPTZ     NOT NULL,
    guest_id        BIGINT          NOT NULL,
    property_id     INT             NOT NULL,
    platform_id     INT             NOT NULL,
    ppl_id          BIGINT          NOT NULL,

    -- -- Thread ids (non-empty JSON array enforced below) -------------------
    thread_ids_json JSONB           NOT NULL,

    -- -- Embedded metadata (JSONB object enforced below) --------------------
    --
    --   Expected shape (all keys optional):
    --   {
    --     "booking_id": "<external booking id string>",
    --     "listing_id": "<external listing id string>",
    --     "status":     "booked" | "cancelled" | ...,
    --     NOTE ABOUT status SEMANTICS:
    --       metadata.status is provider-sourced status (e.g., OwnerRez payload).
    --       It is not rewritten by internal operational workflows such as
    --       checkout scanners or remove-bso cleanup steps.
    --       Internal workflow state (for example "checked out" / inactive for
    --       BSO lifecycle decisions) should be tracked under metadata.bso.*
    --       or a separate explicit internal lifecycle field, so provider truth
    --       and internal state remain distinct.
    --     "bso": {
    --       "cancelled": true,
    --       "potential_extension": {
    --         "last_extended": "2026-03-18T14:00:00+00:00"   <- ISO 8601
    --       }
    --     },
    --     "previous": {
    --       "arrival":  ["<date>", ...],
    --       "property": [<id>, ...]
    --     }
    --   }
    metadata        JSONB           NOT NULL DEFAULT '{}'::JSONB,

    -- -- Timestamps ---------------------------------------------------------
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- -- Foreign key: platform_id must reference a known platform ----------
    CONSTRAINT fk_booking_registers_platform
        FOREIGN KEY (platform_id)
        REFERENCES platforms(id)
        ON DELETE RESTRICT,

    -- -- Foreign key: property_id must reference a known canonical property
    CONSTRAINT fk_booking_registers_property
        FOREIGN KEY (property_id)
        REFERENCES properties(id)
        ON DELETE RESTRICT,

    -- -- Foreign key: ppl_id must reference an exact listing mapping -------
    CONSTRAINT fk_booking_registers_ppl
        FOREIGN KEY (ppl_id)
        REFERENCES platform_property_lookup(id)
        ON DELETE RESTRICT,

    -- -- arrival must be before departure ----------------------------------
    CONSTRAINT chk_booking_registers_dates
        CHECK (arrival < departure),

    -- -- thread_ids_json must be a non-empty JSON array --------------------
    CONSTRAINT chk_booking_registers_thread_ids_non_empty
        CHECK (
            jsonb_typeof(thread_ids_json) = 'array'
            AND jsonb_array_length(thread_ids_json) > 0
        ),

    -- -- metadata must be a JSON object (not array / scalar) ---------------
    CONSTRAINT chk_booking_registers_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

-- ============================================
-- 2) Standard column indexes
-- ============================================

-- Single-column lookups
CREATE INDEX IF NOT EXISTS idx_booking_registers_arrival
    ON booking_registers (arrival);

CREATE INDEX IF NOT EXISTS idx_booking_registers_departure
    ON booking_registers (departure);

CREATE INDEX IF NOT EXISTS idx_booking_registers_ppl_id
    ON booking_registers (ppl_id);

CREATE INDEX IF NOT EXISTS idx_booking_registers_property_id
    ON booking_registers (property_id);

CREATE INDEX IF NOT EXISTS idx_booking_registers_platform_id
    ON booking_registers (platform_id);

CREATE INDEX IF NOT EXISTS idx_booking_registers_guest_id
    ON booking_registers (guest_id);

CREATE INDEX IF NOT EXISTS idx_booking_registers_updated_at
    ON booking_registers (updated_at);

-- Composite: platform + property (common filter combination)
CREATE INDEX IF NOT EXISTS idx_booking_registers_platform_property
    ON booking_registers (platform_id, property_id);

-- Scanner composite: cursor-based pagination over a date window
CREATE INDEX IF NOT EXISTS idx_booking_registers_scanner
    ON booking_registers (arrival, departure, id);

-- ============================================
-- 3) JSONB -- GIN indexes
-- ============================================

-- Full metadata GIN (covers any ad-hoc JSONB operator search)
CREATE INDEX IF NOT EXISTS idx_booking_registers_metadata_gin
    ON booking_registers USING GIN (metadata);

-- Full thread_ids_json GIN
CREATE INDEX IF NOT EXISTS idx_booking_registers_thread_ids_gin
    ON booking_registers USING GIN (thread_ids_json);

-- ============================================
-- 4) JSONB -- expression indexes for targeted searches
-- ============================================

-- Search by metadata.booking_id
--   WHERE metadata->>'booking_id' = '<value>'
CREATE INDEX IF NOT EXISTS idx_booking_registers_meta_booking_id
    ON booking_registers ((metadata->>'booking_id'))
    WHERE metadata->>'booking_id' IS NOT NULL;

-- Enforce one row per (platform, external booking id) when external id exists.
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_registers_platform_external_booking_id
    ON booking_registers (platform_id, (metadata->>'booking_id'))
    WHERE metadata->>'booking_id' IS NOT NULL
      AND BTRIM(metadata->>'booking_id') <> '';

-- Search by metadata.listing_id
--   WHERE metadata->>'listing_id' = '<value>'
CREATE INDEX IF NOT EXISTS idx_booking_registers_meta_listing_id
    ON booking_registers ((metadata->>'listing_id'))
    WHERE metadata->>'listing_id' IS NOT NULL;

-- Search by metadata.bso.cancelled = true
--   WHERE (metadata->'bso'->>'cancelled')::BOOLEAN = TRUE
CREATE INDEX IF NOT EXISTS idx_booking_registers_meta_cancelled
    ON booking_registers ((metadata->'bso'->>'cancelled'))
    WHERE metadata->'bso'->>'cancelled' = 'true';

-- Search / filter by metadata.bso.potential_extension.last_extended
--   WHERE (metadata #>> '{bso,potential_extension,last_extended}')::TIMESTAMPTZ ...
CREATE INDEX IF NOT EXISTS idx_booking_registers_meta_last_extended
    ON booking_registers
        ((metadata #>> '{bso,potential_extension,last_extended}'))
    WHERE metadata #>> '{bso,potential_extension,last_extended}' IS NOT NULL;

-- ============================================
-- 5) Lookup helpers
-- ============================================
CREATE OR REPLACE FUNCTION resolve_booking_register_lookup(
    p_platform_id INT,
    p_listing_id TEXT
) RETURNS TABLE (
    ppl_id BIGINT,
    property_id INT
) AS $$
DECLARE
    v_listing_id TEXT := NULLIF(BTRIM(p_listing_id), '');
BEGIN
    IF p_platform_id IS NULL THEN
        RAISE EXCEPTION 'platform_id is required'
            USING ERRCODE = '22023';
    END IF;

    IF v_listing_id IS NULL THEN
        RAISE EXCEPTION 'listing_id is required'
            USING ERRCODE = '22023';
    END IF;

    RETURN QUERY
    SELECT
        ppl.id::BIGINT,
        ppl.properties_ptr::INT
    FROM platform_property_lookup ppl
    WHERE ppl.platform_id = p_platform_id
      AND ppl.listing_id = v_listing_id
    LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'platform_property_lookup not found for platform_id=% and listing_id=%',
            p_platform_id, v_listing_id
            USING ERRCODE = '23503';
    END IF;
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION normalize_booking_register_metadata(
    p_metadata JSONB,
    p_listing_id TEXT
) RETURNS JSONB AS $$
DECLARE
    v_metadata JSONB := COALESCE(p_metadata, '{}'::JSONB);
    v_listing_id TEXT := NULLIF(BTRIM(p_listing_id), '');
BEGIN
    IF jsonb_typeof(v_metadata) <> 'object' THEN
        RAISE EXCEPTION 'metadata must be a JSON object'
            USING ERRCODE = '22023';
    END IF;

    IF v_listing_id IS NOT NULL THEN
        v_metadata := jsonb_set(v_metadata, '{listing_id}', to_jsonb(v_listing_id), true);
    END IF;

    RETURN v_metadata;
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION enrich_booking_register_stay_metrics(
    p_metadata JSONB,
    p_arrival DATE,
    p_departure DATE,
    p_booked_at TIMESTAMPTZ
) RETURNS JSONB AS $$
DECLARE
    v_metadata JSONB := COALESCE(p_metadata, '{}'::JSONB);
BEGIN
    IF jsonb_typeof(v_metadata) <> 'object' THEN
        RAISE EXCEPTION 'metadata must be a JSON object'
            USING ERRCODE = '22023';
    END IF;

    IF p_arrival IS NOT NULL AND p_departure IS NOT NULL THEN
        v_metadata := jsonb_set(
            v_metadata,
            '{stay_length}',
            to_jsonb((p_departure - p_arrival)::INT),
            true
        );
    END IF;

    IF p_arrival IS NOT NULL AND p_booked_at IS NOT NULL THEN
        v_metadata := jsonb_set(
            v_metadata,
            '{booking_window}',
            to_jsonb(GREATEST((p_arrival - p_booked_at::DATE)::INT, 0)),
            true
        );
    END IF;

    RETURN v_metadata;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ============================================
-- 6) Exact ppl/property mapping validator
--    Validation is based on one exact platform_property_lookup row rather than
--    only checking that some row exists for the same (platform_id, property_id).
-- ============================================
CREATE OR REPLACE FUNCTION validate_booking_registers_ppl()
RETURNS TRIGGER AS $$
DECLARE
    v_lookup_property_id INT;
    v_lookup_platform_id INT;
BEGIN
    SELECT
        ppl.properties_ptr,
        ppl.platform_id
    INTO
        v_lookup_property_id,
        v_lookup_platform_id
    FROM platform_property_lookup ppl
    WHERE ppl.id = NEW.ppl_id;

    IF v_lookup_property_id IS NULL THEN
        RAISE EXCEPTION
            'platform_property_lookup id % was not found',
            NEW.ppl_id
            USING ERRCODE = '23503';
    END IF;

    IF NEW.platform_id IS DISTINCT FROM v_lookup_platform_id THEN
        RAISE EXCEPTION
            'booking_registers.platform_id % does not match platform_property_lookup.platform_id % for ppl_id %',
            NEW.platform_id, v_lookup_platform_id, NEW.ppl_id
            USING ERRCODE = '23514';
    END IF;

    IF NEW.property_id IS DISTINCT FROM v_lookup_property_id THEN
        RAISE EXCEPTION
            'booking_registers.property_id % does not match platform_property_lookup.properties_ptr % for ppl_id %',
            NEW.property_id, v_lookup_property_id, NEW.ppl_id
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_registers_validate_platform_property ON booking_registers;
DROP TRIGGER IF EXISTS trg_booking_registers_validate_ppl ON booking_registers;

CREATE TRIGGER trg_booking_registers_validate_ppl
    BEFORE INSERT OR UPDATE OF property_id, platform_id, ppl_id ON booking_registers
    FOR EACH ROW
    EXECUTE FUNCTION validate_booking_registers_ppl();

-- ============================================
-- 7) Booking CRUD and lookup functions
-- ============================================
CREATE OR REPLACE FUNCTION create_booking_register(
    p_id BIGINT DEFAULT NULL,
    p_type TEXT DEFAULT 'booking',
    p_arrival DATE DEFAULT NULL,
    p_departure DATE DEFAULT NULL,
    p_booked_at TIMESTAMPTZ DEFAULT NULL,
    p_guest_id BIGINT DEFAULT NULL,
    p_platform_id INT DEFAULT NULL,
    p_listing_id TEXT DEFAULT NULL,
    p_thread_ids_json JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT '{}'::JSONB
) RETURNS booking_registers AS $$
DECLARE
    v_lookup RECORD;
    v_metadata JSONB;
    v_row booking_registers%ROWTYPE;
BEGIN
    SELECT *
    INTO v_lookup
    FROM resolve_booking_register_lookup(p_platform_id, p_listing_id);

    v_metadata := enrich_booking_register_stay_metrics(
        normalize_booking_register_metadata(p_metadata, p_listing_id),
        p_arrival,
        p_departure,
        p_booked_at
    );

    IF p_id IS NULL THEN
        INSERT INTO booking_registers (
            type,
            arrival,
            departure,
            booked_at,
            guest_id,
            property_id,
            platform_id,
            ppl_id,
            thread_ids_json,
            metadata
        )
        VALUES (
            COALESCE(NULLIF(BTRIM(p_type), ''), 'booking'),
            p_arrival,
            p_departure,
            p_booked_at,
            p_guest_id,
            v_lookup.property_id,
            p_platform_id,
            v_lookup.ppl_id,
            p_thread_ids_json,
            v_metadata
        )
        RETURNING *
        INTO v_row;
    ELSE
        INSERT INTO booking_registers (
            id,
            type,
            arrival,
            departure,
            booked_at,
            guest_id,
            property_id,
            platform_id,
            ppl_id,
            thread_ids_json,
            metadata
        )
        VALUES (
            p_id,
            COALESCE(NULLIF(BTRIM(p_type), ''), 'booking'),
            p_arrival,
            p_departure,
            p_booked_at,
            p_guest_id,
            v_lookup.property_id,
            p_platform_id,
            v_lookup.ppl_id,
            p_thread_ids_json,
            v_metadata
        )
        RETURNING *
        INTO v_row;
    END IF;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION update_booking_register(
    p_id BIGINT,
    p_type TEXT DEFAULT NULL,
    p_arrival DATE DEFAULT NULL,
    p_departure DATE DEFAULT NULL,
    p_booked_at TIMESTAMPTZ DEFAULT NULL,
    p_guest_id BIGINT DEFAULT NULL,
    p_platform_id INT DEFAULT NULL,
    p_listing_id TEXT DEFAULT NULL,
    p_thread_ids_json JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT NULL
) RETURNS booking_registers AS $$
DECLARE
    v_current booking_registers%ROWTYPE;
    v_current_listing_id TEXT;
    v_lookup RECORD;
    v_type TEXT;
    v_arrival DATE;
    v_departure DATE;
    v_booked_at TIMESTAMPTZ;
    v_metadata JSONB;
    v_row booking_registers%ROWTYPE;
BEGIN
    SELECT *
    INTO v_current
    FROM booking_registers
    WHERE id = p_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'booking_registers id % was not found', p_id
            USING ERRCODE = 'P0002';
    END IF;

    SELECT ppl.listing_id
    INTO v_current_listing_id
    FROM platform_property_lookup ppl
    WHERE ppl.id = v_current.ppl_id;

    IF v_current_listing_id IS NULL THEN
        RAISE EXCEPTION
            'platform_property_lookup id % was not found for booking_registers id %',
            v_current.ppl_id, p_id
            USING ERRCODE = '23503';
    END IF;

    SELECT *
    INTO v_lookup
    FROM resolve_booking_register_lookup(
        COALESCE(p_platform_id, v_current.platform_id),
        COALESCE(NULLIF(BTRIM(p_listing_id), ''), v_current_listing_id)
    );

    v_type := COALESCE(NULLIF(BTRIM(p_type), ''), v_current.type);
    v_arrival := COALESCE(p_arrival, v_current.arrival);
    v_departure := COALESCE(p_departure, v_current.departure);
    v_booked_at := COALESCE(p_booked_at, v_current.booked_at);

    IF p_metadata IS NULL THEN
        v_metadata := COALESCE(v_current.metadata, '{}'::JSONB);
    ELSE
        v_metadata := COALESCE(v_current.metadata, '{}'::JSONB)
            || normalize_booking_register_metadata(p_metadata, NULL);
    END IF;

    v_metadata := normalize_booking_register_metadata(
        v_metadata,
        COALESCE(NULLIF(BTRIM(p_listing_id), ''), v_current_listing_id)
    );
    v_metadata := enrich_booking_register_stay_metrics(
        v_metadata,
        v_arrival,
        v_departure,
        v_booked_at
    );

    UPDATE booking_registers
    SET
        type = v_type,
        arrival = v_arrival,
        departure = v_departure,
        booked_at = v_booked_at,
        guest_id = COALESCE(p_guest_id, v_current.guest_id),
        property_id = v_lookup.property_id,
        platform_id = COALESCE(p_platform_id, v_current.platform_id),
        ppl_id = v_lookup.ppl_id,
        thread_ids_json = COALESCE(p_thread_ids_json, v_current.thread_ids_json),
        metadata = v_metadata
    WHERE id = p_id
    RETURNING *
    INTO v_row;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION upsert_booking_register(
    p_id BIGINT DEFAULT NULL,
    p_type TEXT DEFAULT NULL,
    p_arrival DATE DEFAULT NULL,
    p_departure DATE DEFAULT NULL,
    p_booked_at TIMESTAMPTZ DEFAULT NULL,
    p_guest_id BIGINT DEFAULT NULL,
    p_platform_id INT DEFAULT NULL,
    p_listing_id TEXT DEFAULT NULL,
    p_thread_ids_json JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT NULL
) RETURNS booking_registers AS $$
DECLARE
    v_external_booking_id TEXT := NULLIF(BTRIM(COALESCE(p_metadata->>'booking_id', '')), '');
BEGIN
    IF p_id IS NULL AND p_platform_id IS NOT NULL AND v_external_booking_id IS NOT NULL THEN
        SELECT br.id
        INTO p_id
        FROM booking_registers br
        WHERE br.platform_id = p_platform_id
          AND br.metadata->>'booking_id' = v_external_booking_id
        ORDER BY br.id DESC
        LIMIT 1;
    END IF;

    IF p_id IS NULL THEN
        BEGIN
            RETURN create_booking_register(
                p_id => NULL,
                p_type => COALESCE(p_type, 'booking'),
                p_arrival => p_arrival,
                p_departure => p_departure,
                p_booked_at => p_booked_at,
                p_guest_id => p_guest_id,
                p_platform_id => p_platform_id,
                p_listing_id => p_listing_id,
                p_thread_ids_json => p_thread_ids_json,
                p_metadata => COALESCE(p_metadata, '{}'::jsonb)
            );
        EXCEPTION
            WHEN unique_violation THEN
                IF p_platform_id IS NOT NULL AND v_external_booking_id IS NOT NULL THEN
                    SELECT br.id
                    INTO p_id
                    FROM booking_registers br
                    WHERE br.platform_id = p_platform_id
                      AND br.metadata->>'booking_id' = v_external_booking_id
                    ORDER BY br.id DESC
                    LIMIT 1;
                END IF;

                IF p_id IS NULL THEN
                    RAISE;
                END IF;
        END;
    END IF;

    BEGIN
        RETURN create_booking_register(
            p_id => p_id,
            p_type => COALESCE(p_type, 'booking'),
            p_arrival => p_arrival,
            p_departure => p_departure,
            p_booked_at => p_booked_at,
            p_guest_id => p_guest_id,
            p_platform_id => p_platform_id,
            p_listing_id => p_listing_id,
            p_thread_ids_json => p_thread_ids_json,
            p_metadata => COALESCE(p_metadata, '{}'::jsonb)
        );
    EXCEPTION
        WHEN unique_violation THEN
            RETURN update_booking_register(
                p_id => p_id,
                p_type => p_type,
                p_arrival => p_arrival,
                p_departure => p_departure,
                p_booked_at => p_booked_at,
                p_guest_id => p_guest_id,
                p_platform_id => p_platform_id,
                p_listing_id => p_listing_id,
                p_thread_ids_json => p_thread_ids_json,
                p_metadata => p_metadata
            );
    END;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION get_booking_register_by_id(
    p_id BIGINT
) RETURNS booking_registers AS $$
DECLARE
    v_row booking_registers%ROWTYPE;
BEGIN
    SELECT *
    INTO v_row
    FROM booking_registers
    WHERE id = p_id
    LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'booking_registers id % was not found', p_id
            USING ERRCODE = 'P0002';
    END IF;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION find_booking_registers(
    p_platform_id INT DEFAULT NULL,
    p_metadata_booking_id TEXT DEFAULT NULL,
    p_metadata_listing_id TEXT DEFAULT NULL,
    p_limit INT DEFAULT 100,
    p_cursor BIGINT DEFAULT NULL
) RETURNS SETOF booking_registers AS $$
DECLARE
    v_limit INT := LEAST(GREATEST(COALESCE(p_limit, 100), 1), 500);
BEGIN
    RETURN QUERY
    SELECT *
    FROM booking_registers br
    WHERE (p_platform_id IS NULL OR br.platform_id = p_platform_id)
      AND (p_metadata_booking_id IS NULL OR br.metadata->>'booking_id' = p_metadata_booking_id)
      AND (p_metadata_listing_id IS NULL OR br.metadata->>'listing_id' = p_metadata_listing_id)
      AND (p_cursor IS NULL OR br.id < p_cursor)
    ORDER BY br.id DESC
    LIMIT v_limit;
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION get_booking_registers_by_platform_id(
    p_platform_id INT,
    p_limit INT DEFAULT 100,
    p_cursor BIGINT DEFAULT NULL
) RETURNS SETOF booking_registers AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM find_booking_registers(
        p_platform_id => p_platform_id,
        p_limit => p_limit,
        p_cursor => p_cursor
    );
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION get_booking_registers_by_metadata_booking_id(
    p_metadata_booking_id TEXT,
    p_platform_id INT DEFAULT NULL,
    p_limit INT DEFAULT 100,
    p_cursor BIGINT DEFAULT NULL
) RETURNS SETOF booking_registers AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM find_booking_registers(
        p_platform_id => p_platform_id,
        p_metadata_booking_id => p_metadata_booking_id,
        p_limit => p_limit,
        p_cursor => p_cursor
    );
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION get_booking_registers_by_metadata_listing_id(
    p_metadata_listing_id TEXT,
    p_platform_id INT DEFAULT NULL,
    p_limit INT DEFAULT 100,
    p_cursor BIGINT DEFAULT NULL
) RETURNS SETOF booking_registers AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM find_booking_registers(
        p_platform_id => p_platform_id,
        p_metadata_listing_id => p_metadata_listing_id,
        p_limit => p_limit,
        p_cursor => p_cursor
    );
END;
$$ LANGUAGE plpgsql STABLE;


CREATE OR REPLACE FUNCTION delete_booking_register(
    p_id BIGINT
) RETURNS booking_registers AS $$
DECLARE
    v_row booking_registers%ROWTYPE;
BEGIN
    DELETE FROM booking_registers
    WHERE id = p_id
    RETURNING *
    INTO v_row;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'booking_registers id % was not found', p_id
            USING ERRCODE = 'P0002';
    END IF;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 8) updated_at trigger
--    Only bumps updated_at when a core booking field changes.
--    Metadata-only patches leave updated_at untouched.
-- ============================================
CREATE OR REPLACE FUNCTION set_booking_registers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    IF  NEW.type            IS DISTINCT FROM OLD.type
     OR NEW.arrival         IS DISTINCT FROM OLD.arrival
     OR NEW.departure       IS DISTINCT FROM OLD.departure
     OR NEW.booked_at       IS DISTINCT FROM OLD.booked_at
     OR NEW.guest_id        IS DISTINCT FROM OLD.guest_id
     OR NEW.property_id     IS DISTINCT FROM OLD.property_id
     OR NEW.platform_id     IS DISTINCT FROM OLD.platform_id
     OR NEW.ppl_id          IS DISTINCT FROM OLD.ppl_id
     OR NEW.thread_ids_json IS DISTINCT FROM OLD.thread_ids_json
    THEN
        NEW.updated_at := NOW();
    ELSE
        NEW.updated_at := OLD.updated_at;   -- metadata-only update -> no bump
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_registers_updated_at ON booking_registers;

CREATE TRIGGER trg_booking_registers_updated_at
    BEFORE UPDATE ON booking_registers
    FOR EACH ROW
    EXECUTE FUNCTION set_booking_registers_updated_at();

-- ============================================
-- 9) Example queries (comments only)
-- ============================================
/*
-- (a) By booking entry id
SELECT * FROM booking_registers WHERE id = 12345;

-- (b) By arrival date
SELECT * FROM booking_registers WHERE arrival = '2026-04-01';

-- (c) By departure date
SELECT * FROM booking_registers WHERE departure = '2026-04-07';

-- (d) By date window (scanner pattern)
SELECT * FROM booking_registers
WHERE id > :cursor_id
  AND (
      arrival  BETWEEN :window_start AND :window_end
   OR departure BETWEEN :window_start AND :window_end
  )
ORDER BY id ASC
LIMIT :limit;

-- (e) By ppl_id
SELECT * FROM booking_registers WHERE ppl_id = 42;

-- (f) By property_id
SELECT * FROM booking_registers WHERE property_id = 42;

-- (g) By platform_id
SELECT * FROM booking_registers WHERE platform_id = 7;

-- (h) By metadata.booking_id
SELECT * FROM booking_registers WHERE metadata->>'booking_id' = 'HM-9988';

-- (i) By metadata.listing_id
SELECT * FROM booking_registers WHERE metadata->>'listing_id' = 'ownerrez_prop_1';

-- (j) Cancelled bookings
SELECT * FROM booking_registers
WHERE (metadata->'bso'->>'cancelled')::BOOLEAN = TRUE;

-- (k) Filter by last_extended (scanner exclusion pattern)
SELECT * FROM booking_registers
WHERE NOT (
    (metadata #>> '{bso,potential_extension,last_extended}') IS NOT NULL
    AND updated_at < (metadata #>> '{bso,potential_extension,last_extended}')::TIMESTAMPTZ
);

-- (l) Canonical create/update/get/delete helpers
 SELECT create_booking_register(
     p_id => 9001,
     p_type => 'booking',
    p_arrival => DATE '2026-06-10',
    p_departure => DATE '2026-06-15',
    p_booked_at => TIMESTAMPTZ '2026-05-01T00:00:00Z',
    p_guest_id => 501,
    p_platform_id => 1,
    p_listing_id => 'ownerrez_prop_1',
     p_thread_ids_json => '[1001]'::jsonb,
     p_metadata => '{"booking_id":"OR-123"}'::jsonb
 );

 SELECT upsert_booking_register(
     p_id => 9001,
     p_arrival => DATE '2026-06-11',
     p_departure => DATE '2026-06-16'
 );

 SELECT * FROM get_booking_register_by_id(9001);
 SELECT * FROM get_booking_registers_by_platform_id(1);
 SELECT * FROM get_booking_registers_by_metadata_booking_id('OR-123');
 SELECT * FROM get_booking_registers_by_metadata_listing_id('ownerrez_prop_1');
SELECT delete_booking_register(9001);
*/
